Dev Diaries
===========

The goal of this blog is to track my progression of improving my unix
and workflow.

The first thing is to get my "workbench" under version control. As
always there will be a few dependancies, the best place to highlight
these are to create a README.md and a Gemfile for a ruby tool.

I've come to love tmux, oh-my-zsh, vim, rvm and bundle. Setting up my
environemnt may well get more complex so I'll setup a script that will
check whether these tools are available and install them if they are not.

vim and oh-my-zsh are easy, I already have separate repositories for
these. I'm going to be opinionated for the moment an focus on installing
the other tools via brew and apt. I'll check the OS and use the correct
install recipe accordingly.

I'll start off with a very basic workbench and build it up to the point
where it it optimal for my personal use and configurable enough for
others to do the same too.

This Book
=========

This book is written using using the git-scribe toolchain, which can be found at:

http://github.com/schacon/git-scribe

Instructions on how to install the tool and use it for things like editing this book,
submitting errata and providing translations can be found at that site.